// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYP93o05_pr56KmLupl67recxA4qxDcDY',
    appId: '1:552158130298:web:fd13706ce124ed55f6cbc3',
    messagingSenderId: '552158130298',
    projectId: 'fir-pushnotification-f9031',
    authDomain: 'fir-pushnotification-f9031.firebaseapp.com',
    storageBucket: 'fir-pushnotification-f9031.appspot.com',
    measurementId: 'G-7T0RFN6B65',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7UCmylNAPj5yEQp335OO1XV7udjR1A6s',
    appId: '1:552158130298:android:ada1a797fb891512f6cbc3',
    messagingSenderId: '552158130298',
    projectId: 'fir-pushnotification-f9031',
    storageBucket: 'fir-pushnotification-f9031.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAeLxcRAMpSIT0UzJu5JbfZDwUGTcdo6g',
    appId: '1:552158130298:ios:899ae436c1dfca0af6cbc3',
    messagingSenderId: '552158130298',
    projectId: 'fir-pushnotification-f9031',
    storageBucket: 'fir-pushnotification-f9031.appspot.com',
    iosBundleId: 'com.example.firebasePushNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAeLxcRAMpSIT0UzJu5JbfZDwUGTcdo6g',
    appId: '1:552158130298:ios:899ae436c1dfca0af6cbc3',
    messagingSenderId: '552158130298',
    projectId: 'fir-pushnotification-f9031',
    storageBucket: 'fir-pushnotification-f9031.appspot.com',
    iosBundleId: 'com.example.firebasePushNotification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYP93o05_pr56KmLupl67recxA4qxDcDY',
    appId: '1:552158130298:web:467a5e74c058a199f6cbc3',
    messagingSenderId: '552158130298',
    projectId: 'fir-pushnotification-f9031',
    authDomain: 'fir-pushnotification-f9031.firebaseapp.com',
    storageBucket: 'fir-pushnotification-f9031.appspot.com',
    measurementId: 'G-ZRM1XLDFGV',
  );
}
